# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Snawar Hussain
logo: "/assets/BB.png"
email: sanawar.hussain18@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
teaser: /assets/images/coding_stock.jpg
twitter_username: SanawarHussain
github_username: sanawarhussain
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Snawar Hussain"
  avatar: "/assets/images/snawarhussain.webp"
  bio: "Graduate Student at Central South University
    <br>majoring in Automation
    <br>Research Areas: DeepLearning, Machine learning and image processing"
  location: Changsha, China
  links:
    # - label: "Website"
    #   icon: "fas fa-fw fa-link"
    #   url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/SnawarHussain"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/snawarhussain"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/snawar_hussain"
    # - label: "Changsh,China"
    #   icon: "fas fa-map-marker-alt"
    #   url: "https://twitter.com/SnawarHussain"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/SnawarHussain"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/snawarhussain"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/snawar_hussain"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      words_per_minute: 100
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "facebook"
  facebook:
    appid: 405037007406322 # optional
    num_posts: # 5 (default)
    colorscheme: "dark" # "light" (default), "dark"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-201073195-2"
    anonymize_ip: false # default

social:
  type: # Person or Organization (defaults to Person)
  name: Snawar Hussain # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/SnawarHussain"
    - "https://www.facebook.com/SanawerHussain"
    - "https://instagram.com/snawar_hussain"
    - "https://www.linkedin.com/in/snawarhussain"
atom_feed:
  hide: true
